import Providers from '@/providers/providers'
import '../styles/globals.css'

import type { Metadata } from 'next'
import localFont from 'next/font/local'

const inter = localFont({
  src: '../public/fonts/inter.ttf',
  variable: '--font-inter',
})

export const metadata: Metadata = {
  title: 'Mess Mate',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" suppressHydrationWarning className={inter.variable}>
      <body className="bg-primary-bg text-pure-color font-sans">
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
